services:
  - type: web
    name: roosvelt-remote-signaling
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
